




-- FUNCTIONS CADASTRO

-- PRODUTOS
CREATE OR REPLACE FUNCTION CADASTRAR_PRODUTO(
    P_COD_PROD INT,
    P_NOME_PROD VARCHAR(30)
) RETURNS VARCHAR AS $$
DECLARE
    PRODUTO_EXISTE INT;
    RESULT_MESSAGE VARCHAR;
BEGIN
    SELECT COUNT(*)
    INTO PRODUTO_EXISTE
    FROM PRODUTO
    WHERE NOME_PROD = P_NOME_PROD;

    IF PRODUTO_EXISTE > 0 THEN
        RESULT_MESSAGE := 'ERRO: O NOME DO PRODUTO JÁ EXISTE NA TABELA PRODUTO.';
    ELSE
        INSERT INTO PRODUTO (COD_PROD, NOME_PROD)
        VALUES (P_COD_PROD, P_NOME_PROD);
        
        RESULT_MESSAGE := 'SUCESSO: PRODUTO CADASTRADO COM SUCESSO.';
    END IF;

    RETURN RESULT_MESSAGE;
END;
$$ LANGUAGE plpgsql;

    RETURN RESULT_MESSAGE;
END;


-- CLIENTE 
