CREATE OR REPLACE FUNCTION CADASTRAR_PRODUTO(
    P_COD_PROD INT,
    P_NOME_PROD VARCHAR(30)
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PRODUTO (COD_PROD, NOME_PROD)
    VALUES (P_COD_PROD, P_NOME_PROD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_CLIENTE(
    CLI_COD_CLI INT,
    CLI_NOME_CLI VARCHAR(50),
    CLI_DATA_NASC DATE,
    CLI_TELEFONE VARCHAR(30)
) RETURNS VOID AS $$
BEGIN
    INSERT INTO CLIENTE (COD_CLI, NOME_CLI, DATA_NASC, TELEFONE_CLI)
    VALUES (CLI_COD_CLI, CLI_NOME_CLI, CLI_DATA_NASC, CLI_TELEFONE);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_LOJA(
    L_COD_LOJA INT,
    L_NOME_LOJA VARCHAR(30),
    L_ENDERECO_LOJA VARCHAR(50)
) RETURNS VOID AS $$
BEGIN
    INSERT INTO FLORICULTURA (COD_LOJA, NOME_LOJA, ENDERECO_LOJA)
    VALUES (L_COD_LOJA, L_NOME_LOJA, L_ENDERECO_LOJA);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_FUNCIONARIO(
    F_COD_FUNC INT,
    F_NOME_FUNC VARCHAR(50),
    F_COD_LOJA INT,
    F_TELEFONE VARCHAR(30)
) RETURNS VOID AS $$
BEGIN
    INSERT INTO FUNCIONARIO (COD_FUNC, NOME_FUNC, COD_LOJA, TELEFONE)
    VALUES (F_COD_FUNC, F_NOME_FUNC, F_COD_LOJA, F_TELEFONE);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_FORNECEDOR(
    FORN_COD_FORNECEDOR INT,
    FORN_NOME_FORNECEDOR VARCHAR(30),
    FORN_CONTATO_FORNECEDOR VARCHAR(50)
) RETURNS VOID AS $$
BEGIN
    INSERT INTO FORNECEDOR (COD_FORNECEDOR, NOME_FORNECEDOR, CONTATO_FORNECEDOR)
    VALUES (FORN_COD_FORNECEDOR, FORN_NOME_FORNECEDOR, FORN_CONTATO_FORNECEDOR);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_ESTOQUE(
    E_COD_ESTOQUE INT,
    E_QTD_ESTOQUE INT,
    E_COD_PROD INT,
    E_COD_LOJA INT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO ESTOQUE (COD_ESTOQUE, QUANTIDADE_EST, COD_PROD, COD_LOJA)
    VALUES (E_COD_ESTOQUE, E_QTD_ESTOQUE, E_COD_PROD, E_COD_LOJA);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_VENDA(
    V_COD_VENDA INT,
    V_COD_CLI INT,
    V_COD_FUNC INT,
    V_DATA_VENDA DATE
) RETURNS VOID AS $$
BEGIN
    INSERT INTO VENDA (COD_VENDA, COD_CLI, COD_FUNC, DATA_VENDA)
    VALUES (V_COD_VENDA, V_COD_CLI, V_COD_FUNC, V_DATA_VENDA);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_COMPRA(
    C_COD_COMPRA INT,
    C_COD_ESTOQUE INT,
    C_COD_FUNC INT,
    C_COD_FORNECEDOR INT,
    C_DATA_COMPRA DATE
) RETURNS VOID AS $$
BEGIN
    INSERT INTO COMPRA (COD_COMPRA, COD_ESTOQUE, COD_FUNC, COD_FORNECEDOR, DATA_COMPRA)
    VALUES (C_COD_COMPRA, C_COD_ESTOQUE, C_COD_FUNC, C_COD_FORNECEDOR, C_DATA_COMPRA);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_ITEM_VENDA(
    IV_COD_ITEM_VENDA INT,
    IV_COD_VENDA INT,
    IV_COD_ESTOQUE INT,
    IV_QTD_ITENS_VENDA INT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO ITEM_VENDA (COD_ITEM_VENDA, COD_VENDA, COD_ESTOQUE, QTD_ITENS_VENDA)
    VALUES (IV_COD_ITEM_VENDA, IV_COD_VENDA, IV_COD_ESTOQUE, IV_QTD_ITENS_VENDA);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION CADASTRAR_ITEM_COMPRA(
    IC_COD_ITEM_COMPRA INT,
    IC_COD_COMPRA INT,
    IC_COD_ESTOQUE INT,
    IC_QTD_ITENS_COMPRA INT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO ITEM_COMPRA (COD_ITEM_COMPRA, COD_COMPRA, COD_ESTOQUE, QTD_ITENS_COMPRA)
    VALUES (IC_COD_ITEM_COMPRA, IC_COD_COMPRA, IC_COD_ESTOQUE, IC_QTD_ITENS_COMPRA);
END;
$$ LANGUAGE plpgsql;