CREATE TABLE FLORICULTURA (
    COD_LOJA SERIAL PRIMARY KEY,
    NOME_LOJA VARCHAR(30) NOT NULL,
    ENDERECO_LOJA VARCHAR(50) NOT NULL
);

CREATE TABLE FORNECEDOR (
    COD_FORNECEDOR SERIAL PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(30) NOT NULL,
    CONTATO_FORNECEDOR VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUTO (
    COD_PROD SERIAL PRIMARY KEY,
    NOME_PROD VARCHAR(30) NOT NULL
);

CREATE TABLE ESTOQUE (
    COD_ESTOQUE SERIAL PRIMARY KEY,
    COD_PROD INT NOT NULL,
    QUANTIDADE_EST INT NOT NULL,
    FOREIGN KEY (COD_PROD) REFERENCES PRODUTO(COD_PROD)
);

CREATE INDEX idx_estoque_prod ON ESTOQUE(COD_PROD);

CREATE TABLE FUNCIONARIO (
    COD_FUNC SERIAL PRIMARY KEY,
    NOME_FUNC VARCHAR(50) NOT NULL,
    COD_LOJA INT NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    FOREIGN KEY (COD_LOJA) REFERENCES FLORICULTURA(COD_LOJA)
);

CREATE TABLE CLIENTE (
    COD_CLI SERIAL PRIMARY KEY,
    NOME_CLI VARCHAR(50) NOT NULL,
    TELEFONE_CLI VARCHAR(30) NOT NULL
);

CREATE TABLE VENDA (
    COD_VENDA SERIAL PRIMARY KEY,
    COD_CLI INT NOT NULL,
    COD_FUNC INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI),
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC)
);

CREATE INDEX idx_venda_cliente ON VENDA(COD_CLI);
CREATE INDEX idx_venda_funcionario ON VENDA(COD_FUNC);

CREATE TABLE COMPRA (
    COD_COMPRA SERIAL PRIMARY KEY,
    COD_ESTOQUE INT NOT NULL,
    COD_FUNC INT NOT NULL,
    COD_FORNECEDOR INT NOT NULL,
    DATA_COMPRA DATE NOT NULL,
    FOREIGN KEY (COD_ESTOQUE) REFERENCES ESTOQUE(COD_ESTOQUE),
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

CREATE TABLE ITEM_VENDA (
    COD_ITEM_VENDA SERIAL PRIMARY KEY,
    COD_VENDA INT NOT NULL,
    COD_ESTOQUE INT NOT NULL,
    QTD_ITENS_VENDA INT NOT NULL,
    FOREIGN KEY (COD_VENDA) REFERENCES VENDA(COD_VENDA),
    FOREIGN KEY (COD_ESTOQUE) REFERENCES ESTOQUE(COD_ESTOQUE)
);

CREATE TABLE ITEM_COMPRA (
    COD_ITEM_COMPRA SERIAL PRIMARY KEY,
    COD_COMPRA INT NOT NULL,
    COD_ESTOQUE INT NOT NULL,
    QTD_ITENS_COMPRA INT NOT NULL,
    FOREIGN KEY (COD_COMPRA) REFERENCES COMPRA(COD_COMPRA),
    FOREIGN KEY (COD_ESTOQUE) REFERENCES ESTOQUE(COD_ESTOQUE)
);